### ISSUE TITLE
Crew Members

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/nutshell-nautilus-explorer#3]
# User Stories
- [ ] As a user, I should be able to on board (add) Crew Members to the Nautilus. #15
- [ ] As a user, I should be able to see all Crew Members on the Nautilus. #20
- [ ] As a user, I should be able to edit Crew Members. #19 
- [ ] As a user, I should be able to have a Crew Members disembark (delete) from the Nautilus. #18
