### ISSUE TITLE
Destinations

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/nutshell-nautilus-explorer#4]
# User Stories
- [x] As a user, I should be able to add possible destinations. #29 
- [x] As a user, I should be able to read all possible destinations. #30 
- [x] As a user, I should be able to edit destinations. #31 
- [x] As a user, I should be able to delete a destination. #32
