### ISSUE TITLE
Environmental Data

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/nutshell-nautilus-explorer#6]
# User Stories
- [x] As a user, I should be able to add environmental readings (latitude, longitude, temperature, depth, current, pressure). #25 
- [x] As a user, I should be able to read all environmental readings. #23 
- [ ] As a user, I should be able to edit environmental readings. #24 
- [x] As a user, I should be able to delete an environmental reading. #26
