### ISSUE TITLE
Species

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/nutshell-nautilus-explorer#7]
# User Stories
- [x] As a user, I should be able to add species. #17 
- [x] As a user, I should be able to read all species. #13 
- [x] As a user, I should be able to edit species. #14 
- [x] As a user, I should be able to delete species. #16
